name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/lib-build-release.yml
    with:
      tag: ${{ github.ref_name }}
      mode: ReleaseFast
      publish: true
      